// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BlogPostDocumentDataSlicesSlice =
  | ImageCardsSlice
  | FaqSectionSlice
  | TextBlockGridSlice
  | ImageWithContentSlice
  | ContentBlocksSlice
  | CardGridSlice
  | BannerSlice
  | FormSectionSlice
  | TextContentSlice
  | NewsletterSlice
  | BlogPostsSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Preamble field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.preamble
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  preamble: prismic.KeyTextField;

  /**
   * Rich Text field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.rich_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  rich_text: prismic.RichTextField;

  /**
   * Related Content field in *Blog Post*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.related_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  related_content: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

type FormShapeDocumentDataSlicesSlice =
  | FormSwitchSlice
  | FormTextareaSlice
  | FormOptionsSlice
  | FormNumberSlice
  | FormInputSlice;

/**
 * Content for Form Shape documents
 */
interface FormShapeDocumentData {
  /**
   * Title field in *Form Shape*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_shape.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Preamble field in *Form Shape*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_shape.preamble
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  preamble: prismic.KeyTextField;

  /**
   * Form Action field in *Form Shape*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: form_shape.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<"collect" | "email">;

  /**
   * Submit Text field in *Form Shape*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Submit button text.
   * - **API ID Path**: form_shape.submit_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_text: prismic.KeyTextField;

  /**
   * Submitting Text field in *Form Shape*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Button text while the form is sending.
   * - **API ID Path**: form_shape.submitting_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submitting_text: prismic.KeyTextField;

  /**
   * Submitted Text field in *Form Shape*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Text displayed briefly after form was sent.
   * - **API ID Path**: form_shape.submitted_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submitted_text: prismic.KeyTextField;

  /**
   * Slice Zone field in *Form Shape*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: form_shape.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FormShapeDocumentDataSlicesSlice>;
}

/**
 * Form Shape document from Prismic
 *
 * - **API ID**: `form_shape`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FormShapeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FormShapeDocumentData>,
    "form_shape",
    Lang
  >;

/**
 * Item in *Localization → Resources*
 */
export interface LocalizationDocumentDataResourcesItem {
  /**
   * Key field in *Localization → Resources*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: localization.resources[].key
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  key: prismic.KeyTextField;

  /**
   * Value field in *Localization → Resources*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: localization.resources[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Content for Localization documents
 */
interface LocalizationDocumentData {
  /**
   * Resources field in *Localization*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: localization.resources[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  resources: prismic.GroupField<
    Simplify<LocalizationDocumentDataResourcesItem>
  >;
}

/**
 * Localization document from Prismic
 *
 * - **API ID**: `localization`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LocalizationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LocalizationDocumentData>,
    "localization",
    Lang
  >;

/**
 * Item in *Navigation → Items*
 */
export interface NavigationDocumentDataItemsItem {
  /**
   * Text field in *Navigation → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Link field in *Navigation → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Items field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<NavigationDocumentDataItemsItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | BlogPostsSlice
  | NewsletterSlice
  | FormSectionSlice
  | ContentBlocksSlice
  | TextContentSlice
  | TextBlockGridSlice
  | ImageWithContentSlice
  | FaqSectionSlice
  | ImageCardsSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Rich Text field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.rich_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  rich_text: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Company Email field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.company_email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_email: prismic.KeyTextField;

  /**
   * Company Phone Number field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.company_phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_phone_number: prismic.KeyTextField;

  /**
   * Footer Text field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_text: prismic.KeyTextField;

  /**
   * Blog Listing Page field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.blog_listing_page
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  blog_listing_page: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * SEO Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  seo_description: prismic.KeyTextField;

  /**
   * SEO Keywords field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.seo_keywords
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  seo_keywords: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | BlogPostDocument
  | FormShapeDocument
  | LocalizationDocument
  | NavigationDocument
  | PageDocument
  | SettingsDocument;

/**
 * Item in *Banner → Default → Primary → Buttons*
 */
export interface BannerSliceDefaultPrimaryButtonsItem {
  /**
   * Label field in *Banner → Default → Primary → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.buttons[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Banner → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Type field in *Banner → Default → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: banner.default.primary.buttons[].type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<"primary" | "secondary" | "muted", "filled">;
}

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Image field in *Banner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<"portrait">;

  /**
   * Eyebrow Text field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Text displayed above the title in small letters
   * - **API ID Path**: banner.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Title field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Rich Text field in *Banner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  rich_text: prismic.RichTextField;

  /**
   * Background field in *Banner → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: banner.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<
    "White" | "Light Gray" | "Light Blue" | "Dark",
    "filled"
  >;

  /**
   * Centered field in *Banner → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: banner.default.primary.centered
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  centered: prismic.BooleanField;

  /**
   * Spacing (Top) field in *Banner → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: banner.default.primary.spacing_top
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_top: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Spacing (Bottom) field in *Banner → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: banner.default.primary.spacing_bottom
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_bottom: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Buttons field in *Banner → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<BannerSliceDefaultPrimaryButtonsItem>>;

  /**
   * Boxed field in *Banner → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: banner.default.primary.boxed
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  boxed: prismic.BooleanField;

  /**
   * Background Overlay field in *Banner → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: banner.default.primary.background_overlay
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  background_overlay: prismic.BooleanField;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *BlogPosts → Default → Primary*
 */
export interface BlogPostsSliceDefaultPrimary {
  /**
   * Title field in *BlogPosts → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_posts.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Show All field in *BlogPosts → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_posts.default.primary.show_all
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_all: prismic.BooleanField;

  /**
   * Text field in *BlogPosts → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_posts.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Background field in *BlogPosts → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: blog_posts.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<
    "White" | "Light Gray" | "Light Blue",
    "filled"
  >;

  /**
   * Spacing (Top) field in *BlogPosts → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: blog_posts.default.primary.spacing_top
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_top: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Spacing (Bottom) field in *BlogPosts → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: blog_posts.default.primary.spacing_bottom
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_bottom: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Show All Link field in *BlogPosts → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_posts.default.primary.show_all_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  show_all_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for BlogPosts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogPostsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPosts*
 */
type BlogPostsSliceVariation = BlogPostsSliceDefault;

/**
 * BlogPosts Shared Slice
 *
 * - **API ID**: `blog_posts`
 * - **Description**: BlogPosts
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogPostsSlice = prismic.SharedSlice<
  "blog_posts",
  BlogPostsSliceVariation
>;

/**
 * Primary content in *CardGrid → Default → Primary*
 */
export interface CardGridSliceDefaultPrimary {
  /**
   * Title field in *CardGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *CardGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.default.primary.subTitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subTitle: prismic.KeyTextField;

  /**
   * EyebrowText field in *CardGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.default.primary.eyebrowText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrowText: prismic.KeyTextField;

  /**
   * Background field in *CardGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: card_grid.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<
    "White" | "Light Gray" | "Light Blue" | "Dark",
    "filled"
  >;

  /**
   * Spacing (Top) field in *CardGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: card_grid.default.primary.spacing_top
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_top: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Spacing (Bottom) field in *CardGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: card_grid.default.primary.spacing_bottom
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_bottom: prismic.SelectField<"Large" | "Small" | "None", "filled">;
}

/**
 * Primary content in *CardGrid → Items*
 */
export interface CardGridSliceDefaultItem {
  /**
   * Icon field in *CardGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *CardGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *CardGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Link field in *CardGrid → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Vector HTML field in *CardGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.items[].vector_html
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vector_html: prismic.KeyTextField;
}

/**
 * Default variation for CardGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardGridSliceDefaultPrimary>,
  Simplify<CardGridSliceDefaultItem>
>;

/**
 * Slice variation for *CardGrid*
 */
type CardGridSliceVariation = CardGridSliceDefault;

/**
 * CardGrid Shared Slice
 *
 * - **API ID**: `card_grid`
 * - **Description**: CardGrid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardGridSlice = prismic.SharedSlice<
  "card_grid",
  CardGridSliceVariation
>;

/**
 * Item in *CarouselSection → Default → Primary → Cards*
 */
export interface CarouselSectionSliceDefaultPrimaryCardsItem {
  /**
   * Eyebrow Text field in *CarouselSection → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.cards[].eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Title field in *CarouselSection → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *CarouselSection → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.cards[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Image field in *CarouselSection → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Button Text field in *CarouselSection → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.cards[].button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Primary content in *CarouselSection → Default → Primary*
 */
export interface CarouselSectionSliceDefaultPrimary {
  /**
   * Eyebrow Text field in *CarouselSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Title field in *CarouselSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *CarouselSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Card Type field in *CarouselSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.card_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  card_type: prismic.SelectField<"Horizontal" | "Vertical">;

  /**
   * Background field in *CarouselSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: carousel_section.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<
    "White" | "Light Gray" | "Light Blue" | "Dark",
    "filled"
  >;

  /**
   * Spacing (Top) field in *CarouselSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: carousel_section.default.primary.spacing_top
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_top: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Spacing (Bottom) field in *CarouselSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: carousel_section.default.primary.spacing_bottom
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_bottom: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Cards field in *CarouselSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_section.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<CarouselSectionSliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for CarouselSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarouselSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CarouselSection*
 */
type CarouselSectionSliceVariation = CarouselSectionSliceDefault;

/**
 * CarouselSection Shared Slice
 *
 * - **API ID**: `carousel_section`
 * - **Description**: CarouselSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarouselSectionSlice = prismic.SharedSlice<
  "carousel_section",
  CarouselSectionSliceVariation
>;

/**
 * Item in *ContentBlocks → Default → Primary → Items*
 */
export interface ContentBlocksSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *ContentBlocks → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_blocks.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ContentBlocks → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_blocks.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *ContentBlocks → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_blocks.default.primary.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *ContentBlocks → Default → Primary*
 */
export interface ContentBlocksSliceDefaultPrimary {
  /**
   * Title field in *ContentBlocks → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title displayed above the item grid
   * - **API ID Path**: content_blocks.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *ContentBlocks → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Descriptive text displayed above the item grid
   * - **API ID Path**: content_blocks.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Eyebrow Text field in *ContentBlocks → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_blocks.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Items field in *ContentBlocks → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content_blocks.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<ContentBlocksSliceDefaultPrimaryItemsItem>
  >;

  /**
   * Background field in *ContentBlocks → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: content_blocks.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<
    "White" | "Light Gray" | "Light Blue" | "Dark",
    "filled"
  >;

  /**
   * Spacing (Top) field in *ContentBlocks → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: content_blocks.default.primary.spacing_top
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_top: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Spacing (Bottom) field in *ContentBlocks → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: content_blocks.default.primary.spacing_bottom
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_bottom: prismic.SelectField<"Large" | "Small" | "None", "filled">;
}

/**
 * Default variation for ContentBlocks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentBlocksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentBlocksSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentBlocks*
 */
type ContentBlocksSliceVariation = ContentBlocksSliceDefault;

/**
 * ContentBlocks Shared Slice
 *
 * - **API ID**: `content_blocks`
 * - **Description**: ContentBlocks
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentBlocksSlice = prismic.SharedSlice<
  "content_blocks",
  ContentBlocksSliceVariation
>;

/**
 * Primary content in *FaqSection → Default → Primary*
 */
export interface FaqSectionSliceDefaultPrimary {
  /**
   * Title field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Background field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: faq_section.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<
    "White" | "Light Gray" | "Light Blue" | "Dark",
    "filled"
  >;

  /**
   * Spacing (Top) field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: faq_section.default.primary.spacing_top
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_top: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Spacing (Bottom) field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: faq_section.default.primary.spacing_bottom
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_bottom: prismic.SelectField<"Large" | "Small" | "None", "filled">;
}

/**
 * Primary content in *FaqSection → Items*
 */
export interface FaqSectionSliceDefaultItem {
  /**
   * Question field in *FaqSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FaqSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  answer: prismic.KeyTextField;
}

/**
 * Default variation for FaqSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSectionSliceDefaultPrimary>,
  Simplify<FaqSectionSliceDefaultItem>
>;

/**
 * Slice variation for *FaqSection*
 */
type FaqSectionSliceVariation = FaqSectionSliceDefault;

/**
 * FaqSection Shared Slice
 *
 * - **API ID**: `faq_section`
 * - **Description**: FaqSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSectionSlice = prismic.SharedSlice<
  "faq_section",
  FaqSectionSliceVariation
>;

/**
 * Primary content in *FormInput → Default → Primary*
 */
export interface FormInputSliceDefaultPrimary {
  /**
   * Label field in *FormInput → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_input.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Name field in *FormInput → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_input.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Required field in *FormInput → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_input.default.primary.required
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  required: prismic.KeyTextField;

  /**
   * Placeholder field in *FormInput → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_input.default.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder: prismic.KeyTextField;
}

/**
 * Default variation for FormInput Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormInputSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormInputSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FormInput*
 */
type FormInputSliceVariation = FormInputSliceDefault;

/**
 * FormInput Shared Slice
 *
 * - **API ID**: `form_input`
 * - **Description**: FormInput
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormInputSlice = prismic.SharedSlice<
  "form_input",
  FormInputSliceVariation
>;

/**
 * Primary content in *FormNumber → Default → Primary*
 */
export interface FormNumberSliceDefaultPrimary {
  /**
   * Label field in *FormNumber → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_number.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Name field in *FormNumber → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_number.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Required field in *FormNumber → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_number.default.primary.required
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  required: prismic.KeyTextField;
}

/**
 * Default variation for FormNumber Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormNumberSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormNumberSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FormNumber*
 */
type FormNumberSliceVariation = FormNumberSliceDefault;

/**
 * FormNumber Shared Slice
 *
 * - **API ID**: `form_number`
 * - **Description**: FormNumber
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormNumberSlice = prismic.SharedSlice<
  "form_number",
  FormNumberSliceVariation
>;

/**
 * Item in *FormOptions → Default → Primary → Options*
 */
export interface FormOptionsSliceDefaultPrimaryOptionsItem {
  /**
   * Label field in *FormOptions → Default → Primary → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_options.default.primary.options[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Value field in *FormOptions → Default → Primary → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_options.default.primary.options[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;

  /**
   * Image field in *FormOptions → Default → Primary → Options*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: form_options.default.primary.options[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *FormOptions → Default → Primary*
 */
export interface FormOptionsSliceDefaultPrimary {
  /**
   * Label field in *FormOptions → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_options.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Text field in *FormOptions → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_options.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Options field in *FormOptions → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: form_options.default.primary.options[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  options: prismic.GroupField<
    Simplify<FormOptionsSliceDefaultPrimaryOptionsItem>
  >;
}

/**
 * Default variation for FormOptions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormOptionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormOptionsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FormOptions*
 */
type FormOptionsSliceVariation = FormOptionsSliceDefault;

/**
 * FormOptions Shared Slice
 *
 * - **API ID**: `form_options`
 * - **Description**: FormOptions
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormOptionsSlice = prismic.SharedSlice<
  "form_options",
  FormOptionsSliceVariation
>;

/**
 * Primary content in *Form → Default → Primary*
 */
export interface FormSectionSliceDefaultPrimary {
  /**
   * Form Shape field in *Form → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.default.primary.form_shape
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  form_shape: prismic.ContentRelationshipField;
}

/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Form*
 */
type FormSectionSliceVariation = FormSectionSliceDefault;

/**
 * Form Shared Slice
 *
 * - **API ID**: `form_section`
 * - **Description**: FormSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSectionSlice = prismic.SharedSlice<
  "form_section",
  FormSectionSliceVariation
>;

/**
 * Primary content in *FormSwitch → Default → Primary*
 */
export interface FormSwitchSliceDefaultPrimary {
  /**
   * Label field in *FormSwitch → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_switch.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Name field in *FormSwitch → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_switch.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;
}

/**
 * Default variation for FormSwitch Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSwitchSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormSwitchSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FormSwitch*
 */
type FormSwitchSliceVariation = FormSwitchSliceDefault;

/**
 * FormSwitch Shared Slice
 *
 * - **API ID**: `form_switch`
 * - **Description**: FormSwitch
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSwitchSlice = prismic.SharedSlice<
  "form_switch",
  FormSwitchSliceVariation
>;

/**
 * Primary content in *FormTextarea → Default → Primary*
 */
export interface FormTextareaSliceDefaultPrimary {
  /**
   * Label field in *FormTextarea → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_textarea.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Name field in *FormTextarea → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_textarea.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Placeholder field in *FormTextarea → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_textarea.default.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder: prismic.KeyTextField;
}

/**
 * Default variation for FormTextarea Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormTextareaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormTextareaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FormTextarea*
 */
type FormTextareaSliceVariation = FormTextareaSliceDefault;

/**
 * FormTextarea Shared Slice
 *
 * - **API ID**: `form_textarea`
 * - **Description**: FormTextarea
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormTextareaSlice = prismic.SharedSlice<
  "form_textarea",
  FormTextareaSliceVariation
>;

/**
 * Primary content in *ImageCards → Default → Primary*
 */
export interface ImageCardsSliceDefaultPrimary {
  /**
   * Heading field in *ImageCards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Background field in *ImageCards → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: image_cards.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<
    "White" | "Light Gray" | "Light Blue" | "Dark",
    "filled"
  >;

  /**
   * Spacing (Top) field in *ImageCards → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: image_cards.default.primary.spacing_top
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_top: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Spacing (Bottom) field in *ImageCards → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: image_cards.default.primary.spacing_bottom
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_bottom: prismic.SelectField<"Large" | "Small" | "None", "filled">;
}

/**
 * Primary content in *ImageCards → Items*
 */
export interface ImageCardsSliceDefaultItem {
  /**
   * Title field in *ImageCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *ImageCards → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *ImageCards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *ImageCards → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *ImageCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.items[].buttonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonText: prismic.KeyTextField;
}

/**
 * Default variation for ImageCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageCardsSliceDefaultPrimary>,
  Simplify<ImageCardsSliceDefaultItem>
>;

/**
 * Slice variation for *ImageCards*
 */
type ImageCardsSliceVariation = ImageCardsSliceDefault;

/**
 * ImageCards Shared Slice
 *
 * - **API ID**: `image_cards`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCardsSlice = prismic.SharedSlice<
  "image_cards",
  ImageCardsSliceVariation
>;

/**
 * Item in *ImageWithContent → Default → Primary → Buttons*
 */
export interface ImageWithContentSliceDefaultPrimaryButtonsItem {
  /**
   * Link field in *ImageWithContent → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.default.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Type field in *ImageWithContent → Default → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: image_with_content.default.primary.buttons[].type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<
    "primary" | "secondary" | "muted" | "muted-inverted",
    "filled"
  >;
}

/**
 * Item in *ImageWithContent → Full Width → Primary → Buttons*
 */
export interface ImageWithContentSliceFullWidthPrimaryButtonsItem {
  /**
   * Link field in *ImageWithContent → Full Width → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.fullWidth.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Type field in *ImageWithContent → Full Width → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: image_with_content.fullWidth.primary.buttons[].type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<
    "primary" | "secondary" | "muted" | "muted-inverted",
    "filled"
  >;
}

/**
 * Item in *ImageWithContent → Vertical → Primary → Buttons*
 */
export interface ImageWithContentSliceVerticalPrimaryButtonsItem {
  /**
   * Link field in *ImageWithContent → Vertical → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.vertical.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Type field in *ImageWithContent → Vertical → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: image_with_content.vertical.primary.buttons[].type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<
    "primary" | "secondary" | "muted" | "muted-inverted",
    "filled"
  >;
}

/**
 * Primary content in *ImageWithContent → Default → Primary*
 */
export interface ImageWithContentSliceDefaultPrimary {
  /**
   * Section Title field in *ImageWithContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Displayed above the image & content.
   * - **API ID Path**: image_with_content.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Description field in *ImageWithContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Displayed above the image & content.
   * - **API ID Path**: image_with_content.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_description: prismic.KeyTextField;

  /**
   * Title field in *ImageWithContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Eyebrow Text field in *ImageWithContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Rich Text field in *ImageWithContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.default.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  rich_text: prismic.RichTextField;

  /**
   * Image field in *ImageWithContent → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Direction field in *ImageWithContent → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.default.primary.direction
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  direction: prismic.SelectField<"normal" | "reverse">;

  /**
   * Background field in *ImageWithContent → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: image_with_content.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<
    "White" | "Light Gray" | "Light Blue",
    "filled"
  >;

  /**
   * Spacing (Top) field in *ImageWithContent → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: image_with_content.default.primary.spacing_top
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_top: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Spacing (Bottom) field in *ImageWithContent → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: image_with_content.default.primary.spacing_bottom
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_bottom: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Buttons field in *ImageWithContent → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<
    Simplify<ImageWithContentSliceDefaultPrimaryButtonsItem>
  >;

  /**
   * Object Contain field in *ImageWithContent → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_with_content.default.primary.object_contain
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  object_contain: prismic.BooleanField;
}

/**
 * Default variation for ImageWithContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageWithContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageWithContentSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageWithContent → Full Width → Primary*
 */
export interface ImageWithContentSliceFullWidthPrimary {
  /**
   * Section Title field in *ImageWithContent → Full Width → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Displayed above the image & content.
   * - **API ID Path**: image_with_content.fullWidth.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Description field in *ImageWithContent → Full Width → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Displayed above the image & content.
   * - **API ID Path**: image_with_content.fullWidth.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_description: prismic.KeyTextField;

  /**
   * Title field in *ImageWithContent → Full Width → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.fullWidth.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Eyebrow Text field in *ImageWithContent → Full Width → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.fullWidth.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Rich Text field in *ImageWithContent → Full Width → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.fullWidth.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  rich_text: prismic.RichTextField;

  /**
   * Image field in *ImageWithContent → Full Width → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.fullWidth.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Direction field in *ImageWithContent → Full Width → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.fullWidth.primary.direction
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  direction: prismic.SelectField<"normal" | "reverse">;

  /**
   * Buttons field in *ImageWithContent → Full Width → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.fullWidth.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<
    Simplify<ImageWithContentSliceFullWidthPrimaryButtonsItem>
  >;
}

/**
 * Full Width variation for ImageWithContent Slice
 *
 * - **API ID**: `fullWidth`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageWithContentSliceFullWidth = prismic.SharedSliceVariation<
  "fullWidth",
  Simplify<ImageWithContentSliceFullWidthPrimary>,
  never
>;

/**
 * Primary content in *ImageWithContent → Vertical → Primary*
 */
export interface ImageWithContentSliceVerticalPrimary {
  /**
   * Section Title field in *ImageWithContent → Vertical → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Displayed above the image & content.
   * - **API ID Path**: image_with_content.vertical.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Description field in *ImageWithContent → Vertical → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Displayed above the image & content.
   * - **API ID Path**: image_with_content.vertical.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_description: prismic.KeyTextField;

  /**
   * Title field in *ImageWithContent → Vertical → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.vertical.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Eyebrow Text field in *ImageWithContent → Vertical → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.vertical.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Rich Text field in *ImageWithContent → Vertical → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.vertical.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  rich_text: prismic.RichTextField;

  /**
   * Image field in *ImageWithContent → Vertical → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.vertical.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Background field in *ImageWithContent → Vertical → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: image_with_content.vertical.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<
    "White" | "Light Gray" | "Light Blue",
    "filled"
  >;

  /**
   * Spacing (Top) field in *ImageWithContent → Vertical → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: image_with_content.vertical.primary.spacing_top
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_top: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Spacing (Bottom) field in *ImageWithContent → Vertical → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: image_with_content.vertical.primary.spacing_bottom
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_bottom: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Buttons field in *ImageWithContent → Vertical → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_content.vertical.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<
    Simplify<ImageWithContentSliceVerticalPrimaryButtonsItem>
  >;

  /**
   * Object Contain field in *ImageWithContent → Vertical → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_with_content.vertical.primary.object_contain
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  object_contain: prismic.BooleanField;
}

/**
 * Vertical variation for ImageWithContent Slice
 *
 * - **API ID**: `vertical`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageWithContentSliceVertical = prismic.SharedSliceVariation<
  "vertical",
  Simplify<ImageWithContentSliceVerticalPrimary>,
  never
>;

/**
 * Slice variation for *ImageWithContent*
 */
type ImageWithContentSliceVariation =
  | ImageWithContentSliceDefault
  | ImageWithContentSliceFullWidth
  | ImageWithContentSliceVertical;

/**
 * ImageWithContent Shared Slice
 *
 * - **API ID**: `image_with_content`
 * - **Description**: ImageWithContent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageWithContentSlice = prismic.SharedSlice<
  "image_with_content",
  ImageWithContentSliceVariation
>;

/**
 * Item in *Motivators → Default → Primary → Items*
 */
export interface MotivatorsSliceDefaultPrimaryItemsItem {
  /**
   * Title field in *Motivators → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: motivators.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Motivators → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: motivators.default.primary.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Icon field in *Motivators → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: motivators.default.primary.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Vector Icon field in *Motivators → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: motivators.default.primary.items[].vector_icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vector_icon: prismic.KeyTextField;
}

/**
 * Primary content in *Motivators → Default → Primary*
 */
export interface MotivatorsSliceDefaultPrimary {
  /**
   * Background field in *Motivators → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: motivators.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<
    "White" | "Light Gray" | "Light Blue" | "Dark",
    "filled"
  >;

  /**
   * Spacing (Top) field in *Motivators → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: motivators.default.primary.spacing_top
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_top: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Spacing (Bottom) field in *Motivators → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: motivators.default.primary.spacing_bottom
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_bottom: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Items field in *Motivators → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: motivators.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<MotivatorsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Motivators Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MotivatorsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MotivatorsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Motivators*
 */
type MotivatorsSliceVariation = MotivatorsSliceDefault;

/**
 * Motivators Shared Slice
 *
 * - **API ID**: `motivators`
 * - **Description**: Motivators
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MotivatorsSlice = prismic.SharedSlice<
  "motivators",
  MotivatorsSliceVariation
>;

/**
 * Item in *StatsSection → Default → Primary → Items*
 */
export interface StatsSectionSliceDefaultPrimaryItemsItem {
  /**
   * Label field in *StatsSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_section.default.primary.items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Number field in *StatsSection → Default → Primary → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_section.default.primary.items[].number
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  number: prismic.NumberField;
}

/**
 * Primary content in *StatsSection → Default → Primary*
 */
export interface StatsSectionSliceDefaultPrimary {
  /**
   * Title field in *StatsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Background field in *StatsSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: stats_section.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<
    "White" | "Light Gray" | "Light Blue" | "Dark",
    "filled"
  >;

  /**
   * Spacing (Top) field in *StatsSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: stats_section.default.primary.spacing_top
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_top: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Spacing (Bottom) field in *StatsSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: stats_section.default.primary.spacing_bottom
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_bottom: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Items field in *StatsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<StatsSectionSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for StatsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StatsSection*
 */
type StatsSectionSliceVariation = StatsSectionSliceDefault;

/**
 * StatsSection Shared Slice
 *
 * - **API ID**: `stats_section`
 * - **Description**: StatsSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsSectionSlice = prismic.SharedSlice<
  "stats_section",
  StatsSectionSliceVariation
>;

/**
 * Primary content in *TextBlockGrid → Default → Primary*
 */
export interface TextBlockGridSliceDefaultPrimary {
  /**
   * Title field in *TextBlockGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *TextBlockGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_grid.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Eyebrow Text field in *TextBlockGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_grid.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Background field in *TextBlockGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: text_block_grid.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<
    "White" | "Light Gray" | "Light Blue" | "Dark",
    "filled"
  >;

  /**
   * Spacing (Top) field in *TextBlockGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: text_block_grid.default.primary.spacing_top
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_top: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Spacing (Bottom) field in *TextBlockGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: text_block_grid.default.primary.spacing_bottom
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_bottom: prismic.SelectField<"Large" | "Small" | "None", "filled">;
}

/**
 * Primary content in *TextBlockGrid → Items*
 */
export interface TextBlockGridSliceDefaultItem {
  /**
   * Title field in *TextBlockGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_grid.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *TextBlockGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_grid.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Vector HTML field in *TextBlockGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_grid.items[].vector_html
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vector_html: prismic.KeyTextField;

  /**
   * Link field in *TextBlockGrid → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_grid.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for TextBlockGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockGridSliceDefaultPrimary>,
  Simplify<TextBlockGridSliceDefaultItem>
>;

/**
 * Primary content in *TextBlockGrid → Grid - With Images → Primary*
 */
export interface TextBlockGridSliceGridWithImagesPrimary {
  /**
   * Title field in *TextBlockGrid → Grid - With Images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_grid.gridWithImages.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *TextBlockGrid → Grid - With Images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_grid.gridWithImages.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Eyebrow Text field in *TextBlockGrid → Grid - With Images → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_grid.gridWithImages.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;
}

/**
 * Primary content in *TextBlockGrid → Items*
 */
export interface TextBlockGridSliceGridWithImagesItem {
  /**
   * Title field in *TextBlockGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_grid.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *TextBlockGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_grid.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Image field in *TextBlockGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_grid.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Grid - With Images variation for TextBlockGrid Slice
 *
 * - **API ID**: `gridWithImages`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockGridSliceGridWithImages = prismic.SharedSliceVariation<
  "gridWithImages",
  Simplify<TextBlockGridSliceGridWithImagesPrimary>,
  Simplify<TextBlockGridSliceGridWithImagesItem>
>;

/**
 * Slice variation for *TextBlockGrid*
 */
type TextBlockGridSliceVariation =
  | TextBlockGridSliceDefault
  | TextBlockGridSliceGridWithImages;

/**
 * TextBlockGrid Shared Slice
 *
 * - **API ID**: `text_block_grid`
 * - **Description**: TextBlockGrid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockGridSlice = prismic.SharedSlice<
  "text_block_grid",
  TextBlockGridSliceVariation
>;

/**
 * Primary content in *TextContent → Default → Primary*
 */
export interface TextContentSliceDefaultPrimary {
  /**
   * Title field in *TextContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Preamble field in *TextContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_content.default.primary.preamble
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  preamble: prismic.KeyTextField;

  /**
   * Rich Text field in *TextContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_content.default.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  rich_text: prismic.RichTextField;

  /**
   * Background field in *TextContent → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: text_content.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<
    "White" | "Light Gray" | "Light Blue",
    "filled"
  >;

  /**
   * Spacing (Top) field in *TextContent → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: text_content.default.primary.spacing_top
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_top: prismic.SelectField<"Large" | "Small" | "None", "filled">;

  /**
   * Spacing (Bottom) field in *TextContent → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: text_content.default.primary.spacing_bottom
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing_bottom: prismic.SelectField<"Large" | "Small" | "None", "filled">;
}

/**
 * Default variation for TextContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextContent*
 */
type TextContentSliceVariation = TextContentSliceDefault;

/**
 * TextContent Shared Slice
 *
 * - **API ID**: `text_content`
 * - **Description**: TextContent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextContentSlice = prismic.SharedSlice<
  "text_content",
  TextContentSliceVariation
>;

/**
 * Primary content in *TitleWithText → Default → Primary*
 */
export interface TitleWithTextSliceDefaultPrimary {
  /**
   * Title field in *TitleWithText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Rich Text field in *TitleWithText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.default.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  rich_text: prismic.RichTextField;

  /**
   * Eyebrow Text field in *TitleWithText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;
}

/**
 * Default variation for TitleWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TitleWithTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleWithTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TitleWithText*
 */
type TitleWithTextSliceVariation = TitleWithTextSliceDefault;

/**
 * TitleWithText Shared Slice
 *
 * - **API ID**: `title_with_text`
 * - **Description**: TitleWithText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TitleWithTextSlice = prismic.SharedSlice<
  "title_with_text",
  TitleWithTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      FormShapeDocument,
      FormShapeDocumentData,
      FormShapeDocumentDataSlicesSlice,
      LocalizationDocument,
      LocalizationDocumentData,
      LocalizationDocumentDataResourcesItem,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataItemsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimaryButtonsItem,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      BlogPostsSlice,
      BlogPostsSliceDefaultPrimary,
      BlogPostsSliceVariation,
      BlogPostsSliceDefault,
      CardGridSlice,
      CardGridSliceDefaultPrimary,
      CardGridSliceDefaultItem,
      CardGridSliceVariation,
      CardGridSliceDefault,
      CarouselSectionSlice,
      CarouselSectionSliceDefaultPrimaryCardsItem,
      CarouselSectionSliceDefaultPrimary,
      CarouselSectionSliceVariation,
      CarouselSectionSliceDefault,
      ContentBlocksSlice,
      ContentBlocksSliceDefaultPrimaryItemsItem,
      ContentBlocksSliceDefaultPrimary,
      ContentBlocksSliceVariation,
      ContentBlocksSliceDefault,
      FaqSectionSlice,
      FaqSectionSliceDefaultPrimary,
      FaqSectionSliceDefaultItem,
      FaqSectionSliceVariation,
      FaqSectionSliceDefault,
      FormInputSlice,
      FormInputSliceDefaultPrimary,
      FormInputSliceVariation,
      FormInputSliceDefault,
      FormNumberSlice,
      FormNumberSliceDefaultPrimary,
      FormNumberSliceVariation,
      FormNumberSliceDefault,
      FormOptionsSlice,
      FormOptionsSliceDefaultPrimaryOptionsItem,
      FormOptionsSliceDefaultPrimary,
      FormOptionsSliceVariation,
      FormOptionsSliceDefault,
      FormSectionSlice,
      FormSectionSliceDefaultPrimary,
      FormSectionSliceVariation,
      FormSectionSliceDefault,
      FormSwitchSlice,
      FormSwitchSliceDefaultPrimary,
      FormSwitchSliceVariation,
      FormSwitchSliceDefault,
      FormTextareaSlice,
      FormTextareaSliceDefaultPrimary,
      FormTextareaSliceVariation,
      FormTextareaSliceDefault,
      ImageCardsSlice,
      ImageCardsSliceDefaultPrimary,
      ImageCardsSliceDefaultItem,
      ImageCardsSliceVariation,
      ImageCardsSliceDefault,
      ImageWithContentSlice,
      ImageWithContentSliceDefaultPrimaryButtonsItem,
      ImageWithContentSliceDefaultPrimary,
      ImageWithContentSliceFullWidthPrimaryButtonsItem,
      ImageWithContentSliceFullWidthPrimary,
      ImageWithContentSliceVerticalPrimaryButtonsItem,
      ImageWithContentSliceVerticalPrimary,
      ImageWithContentSliceVariation,
      ImageWithContentSliceDefault,
      ImageWithContentSliceFullWidth,
      ImageWithContentSliceVertical,
      MotivatorsSlice,
      MotivatorsSliceDefaultPrimaryItemsItem,
      MotivatorsSliceDefaultPrimary,
      MotivatorsSliceVariation,
      MotivatorsSliceDefault,
      StatsSectionSlice,
      StatsSectionSliceDefaultPrimaryItemsItem,
      StatsSectionSliceDefaultPrimary,
      StatsSectionSliceVariation,
      StatsSectionSliceDefault,
      TextBlockGridSlice,
      TextBlockGridSliceDefaultPrimary,
      TextBlockGridSliceDefaultItem,
      TextBlockGridSliceGridWithImagesPrimary,
      TextBlockGridSliceGridWithImagesItem,
      TextBlockGridSliceVariation,
      TextBlockGridSliceDefault,
      TextBlockGridSliceGridWithImages,
      TextContentSlice,
      TextContentSliceDefaultPrimary,
      TextContentSliceVariation,
      TextContentSliceDefault,
      TitleWithTextSlice,
      TitleWithTextSliceDefaultPrimary,
      TitleWithTextSliceVariation,
      TitleWithTextSliceDefault,
    };
  }
}
