// Code generated by Slice Machine. DO NOT EDIT.

import Banner from "./Banner";
import BlogPosts from "./BlogPosts";
import CardGrid from "./CardGrid";
import CarouselSection from "./CarouselSection";
import ContentBlocks from "./ContentBlocks";
import FaqSection from "./FaqSection";
import FormInput from "./FormInput";
import FormNumber from "./FormNumber";
import FormOptions from "./FormOptions";
import Form from "./Form";
import FormSwitch from "./FormSwitch";
import FormTextarea from "./FormTextarea";
import ImageCards from "./ImageCards";
import ImageWithContent from "./ImageWithContent";
import Motivators from "./Motivators";
import StatsSection from "./StatsSection";
import TextBlockGrid from "./TextBlockGrid";
import TextContent from "./TextContent";
import TitleWithText from "./TitleWithText";

export const components = {
  banner: Banner,
  blog_posts: BlogPosts,
  card_grid: CardGrid,
  carousel_section: CarouselSection,
  content_blocks: ContentBlocks,
  faq_section: FaqSection,
  form_input: FormInput,
  form_number: FormNumber,
  form_options: FormOptions,
  form_section: Form,
  form_switch: FormSwitch,
  form_textarea: FormTextarea,
  image_cards: ImageCards,
  image_with_content: ImageWithContent,
  motivators: Motivators,
  stats_section: StatsSection,
  text_block_grid: TextBlockGrid,
  text_content: TextContent,
  title_with_text: TitleWithText,
};
